### ISSUE TITLE
Virus total detect 

### ISSUE THREAD

**Issue by matheuschimelli** [YasserGersy/cazador_unr#1]
![image](https://user-images.githubusercontent.com/10470074/65774196-26ea5e00-e114-11e9-86c4-c76c9f775825.png)

**Comment by YasserGersy** [comment]
Hi @matheuschimelli  , Are you sure you uploaded the correct file or you stumbled across a link from search engine ? 

The current version of cazador is bigger than 5 Mbs  thanks to the  lists   embedded  in fuzzers , The size  of the file in your screenshot is less than 2 mbs and  i update the app daily so i can not make sure if the hash matches one of the old versions.

https://www.virustotal.com/gui/url/a0c1f1409feec13ced98dc546ac52ac304c4beee90115bc0355f37d6ea00a6b7/detection
