### ISSUE TITLE
plugin EmailHunter

### ISSUE THREAD

**Issue by mhmh55516** [YasserGersy/cazador_unr#2]
When select all and try to copy Emails nothing happen in clipboard
please fix it.
Thx

**Comment by YasserGersy** [comment]
Kindly Make sure you have the latest pushed  version of CazGuiLib.dll file  Which is responsible to handle the  copy operation. Btw you can use CTRL+C , it works if you are not selecting all rows.

**Comment by YasserGersy** [comment]
Closing...
